# Generated by Django 3.1.7 on 2021-04-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('open', models.FloatField(blank=True, default=0)),
                ('high', models.FloatField(blank=True, default=0)),
                ('low', models.FloatField(blank=True, default=0)),
                ('close', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
