# Generated by Django 3.2 on 2021-04-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
